### ISSUE TITLE
Add more card for Movies

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/Movies-Collection#1]
Please read the readme file carefully before contributing. If you have any doubts, you can ask here

**Comment by Utkarsh212** [comment]
Please assign this issue to me so that I can start working on this

**Comment by vikhyatsingh123** [comment]
@Utkarsh212 You can start working. no need to assign

**Comment by YashSachan2** [comment]
@vikhyatsingh123 Can I work on it under Codepeak-23?

**Comment by YashSachan2** [comment]
@vikhyatsingh123 I have made a pr adding Dark Knight Movie Card .Please assign points to me under Codepeak-23

**Comment by singhcoder694** [comment]
@vikhyatsingh123 can we add more web series and movies card now also?

**Comment by vikhyatsingh123** [comment]
@singhcoder694 yes
