### ISSUE TITLE
Enhancing the User Interface

### ISSUE THREAD

**Issue by Harsh2504** [vikhyatsingh123/Movies-Collection#19]
I can contribute for these improvements:
1. Navbar should have website title 
2. Navbar styling , hover effects , active tab
3. Dark mode to work properly on whole website
4. Carsouel improvement (picture scaling )
5. Improve overall styling of webpage (buttons , fonts ,etc);

Adding abouts page with Project owner info and website purpose.

**Comment by vikhyatsingh123** [comment]
Give me expected time for creating pr

**Comment by Harsh2504** [comment]
Probably by the end of second week of code peak (21 dec-22dec) I’m working on multiple contributions so it will take a time

**Comment by vikhyatsingh123** [comment]
Other contributors are asking to work on these issues. So, I will suggest choose one issue and complete it before asking for another issue

**Comment by Harsh2504** [comment]
> Other contributors are asking to work on these issues. So, I will suggest choose one issue and complete it before asking for another issue

Yeah yeah I’m now focusing on these issues only not going for another until I complete this

**Comment by Harsh2504** [comment]
> > Other contributors are asking to work on these issues. So, I will suggest choose one issue and complete it before asking for another issue
> 
> Yeah yeah I’m now focusing on these issues only not going for another until I complete these

**Comment by Harsh2504** [comment]
**Progress up till now:**
i will complete this and start working on your naruto project 
Was very busy now due to exams bt will try to manage.
Also I have  **created the logic** for **adding cards dynamically** so after this pr I will merge that too !!!

**Tell me feedback does it look better than previous design!!!**

![image](https://github.com/vikhyatsingh123/Movies-Collection/assets/104843006/741853c9-1d07-4de7-88ec-99bc7446b62b)

![image](https://github.com/vikhyatsingh123/Movies-Collection/assets/104843006/60b57734-c5f2-4cb8-84ef-4e93061cd85b)

![image](https://github.com/vikhyatsingh123/Movies-Collection/assets/104843006/238158bb-09ba-40f0-ae3e-010d05d07f9b)

![image](https://github.com/vikhyatsingh123/Movies-Collection/assets/104843006/2f2077a3-71c1-4d38-af23-b1410f693ed9)

![image](https://github.com/vikhyatsingh123/Movies-Collection/assets/104843006/68c538d0-3cb3-4c03-9640-e3cc6ea0a579)

![image](https://github.com/vikhyatsingh123/Movies-Collection/assets/104843006/a3fb7108-4951-4ec8-9742-4a74c7321a2e)

**Comment by vikhyatsingh123** [comment]
Yeah, the design is looking perfect. 
Can you add home,about in rightmost side of header instead of middle. (switch header about)
In dark mode, text color is not properly visible.You can choose white text color
