### ISSUE TITLE
About Page not Working

### ISSUE THREAD

**Issue by singhcoder694** [vikhyatsingh123/Movies-Collection#23]
**About page is not opening** since the routers are not fixed. As well as it doesn't have much content to show. I would like to work on About page and take this website one step ahead....

<img width="939" alt="Screenshot 2023-12-11 081511" src="https://github.com/vikhyatsingh123/Movies-Collection/assets/114601400/6edf3105-96f5-456e-9962-0bf86d7380dc">

**Comment by vikhyatsingh123** [comment]
ok, go ahead
