### ISSUE TITLE
Home and About button trasparency

### ISSUE THREAD

**Issue by singhcoder694** [vikhyatsingh123/Movies-Collection#24]
When clicked on Home / About button it disappears due to some issue when website is in Light Mode . I would like to contribute in this under CodePeak'23
<img width="939" alt="Screenshot 2023-12-11 081635" src="https://github.com/vikhyatsingh123/Movies-Collection/assets/114601400/549e68ab-c446-4d58-8fb5-db95c6058bba">

**Comment by vikhyatsingh123** [comment]
Someone is working on this issue. You can pick another issue. Or simply add new cards
