### ISSUE TITLE
Add Suggestion Page for Users

### ISSUE THREAD

**Issue by singhcoder694** [vikhyatsingh123/Movies-Collection#28]
It would be nice if in the website contents are added on basis of Demand coming from users. For this we can make a Suggestion page in which Users will provide the name of movies which they want to see on website. This will play a key role in enhancing User Experience.

**Comment by vikhyatsingh123** [comment]
Instead of making another page, we can add search box in header which filter out movies based on name

**Comment by singhcoder694** [comment]
But that will only provide list of movies on the website... What if user wants a movie that is not listed on website for that case I was saying this idea...

**Comment by vikhyatsingh123** [comment]
oh, so you are saying to fetch data from internet

**Comment by singhcoder694** [comment]
No, I am saying lets say user suggest to add Avenger so using suggestion form on website he can reach to team of website and as they feel demand for this movie is high they will add a new card for that movie....

**Comment by vikhyatsingh123** [comment]
oh, this is nice idea. You can implement that

**Comment by singhcoder694** [comment]
Thanks for your support 😊 you may assign me this under CodePeak'23.
Suggestion form will be functional as I will be adding there dynamic mailing, as user clicks the send button it will reach to website team 🚀🚀

**Comment by Ayusht777** [comment]
does this website is live

**Comment by singhcoder694** [comment]
No @Ayusht777 I guess...

**Comment by singhcoder694** [comment]
@vikhyatsingh123 sir I haven't get any point for this PR yet... and there is one more in Naruto Repo also.
