### ISSUE TITLE
adding unique cards on page as banner, and enhancing existing banner

### ISSUE THREAD

**Issue by Sami3160** [vikhyatsingh123/Movies-Collection#30]
ill be adding some unique cards, with behavior like banner, 
every cards will be with some unique content, and can be slided by mouse or keyboard
i wont be replacing original banner, just adding this component below your banner.
 And ill enhance the existing banner with better images, text on it and some filters
it will look something like:
![289268887-2f869b09-a8ac-4779-9c64-1efa1d71d1e7](https://github.com/vikhyatsingh123/Movies-Collection/assets/110652247/bb259b48-a3d9-4ffd-873a-518d1d12a662)

Cards will be responsive, with minimal code and various customization options by coding.
Well i have implemented this on someone else project also, and the results were awesome.

**Comment by vikhyatsingh123** [comment]
sure, also upload screenshot in your pr
