### ISSUE TITLE
modify the design of suggest page

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/Movies-Collection#31]

**Comment by PSS2134** [comment]
Hey I can work on this @vikhyatsingh123! Can you assign me this

**Comment by vikhyatsingh123** [comment]
sure

**Comment by PSS2134** [comment]
I would be contributing under Codepeak'23 @vikhyatsingh123

**Comment by PSS2134** [comment]
![Screenshot 2023-12-20 163648](https://github.com/vikhyatsingh123/Movies-Collection/assets/101321904/3660c29a-4561-4574-a0af-35c1e7c8ead8)
Is this fine? @vikhyatsingh123

**Comment by PSS2134** [comment]
I have created  PR @vikhyatsingh123 , Can you add the problem label for this issue

**Comment by PSS2134** [comment]
#43

**Comment by PSS2134** [comment]
@vikhyatsingh123 Haven't received the points for this one ?
