### ISSUE TITLE
Adding a hosted link of the website to the repository

### ISSUE THREAD

**Issue by drockparashar** [vikhyatsingh123/Movies-Collection#37]
The website currently does not have a hosted link. Adding a live link will boost the reach of the website and enable contributors to track live progress of this website. I am currently contributing under codepeak 23.

**Comment by drockparashar** [comment]
Here is the link for the deployed link of the website:- https://movies-collection-pi.vercel.app/
You can add this to the About section of this repository.

**Comment by vikhyatsingh123** [comment]
Thanks, I will give points related to it
