### ISSUE TITLE
A modern logo

### ISSUE THREAD

**Issue by AaadityaG** [vikhyatsingh123/Movies-Collection#51]
Please allow me to work on it for codepeak

**Comment by vikhyatsingh123** [comment]
like what. share the image here

**Comment by AaadityaG** [comment]
Like this one

![Movies Collection (1)](https://github.com/vikhyatsingh123/Movies-Collection/assets/114663382/be20879d-460a-48b8-9e47-aca178a8a8d1)
![Movies Collection](https://github.com/vikhyatsingh123/Movies-Collection/assets/114663382/1ce62ce7-f81c-4108-9e0e-bb3a4b22549c)

**Comment by AaadityaG** [comment]
You like it or not
