### ISSUE TITLE
A movie API to fetch the data of movies

### ISSUE THREAD

**Issue by PSS2134** [vikhyatsingh123/Movies-Collection#59]
We can add all the movie data into a API and can also keep posting the suggested one there after a user clicks on suggested form
@vikhyatsingh123

**Comment by vikhyatsingh123** [comment]
If you want to work on this one, you can do even after codepeak

**Comment by PSS2134** [comment]
Yes , I have created all data into json could you check the pr #67

**Comment by vikhyatsingh123** [comment]
great. Can you make a more pr for updated readme according to code
